=== atfaber/michelecasalgrandiresume/resume_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "name": {
            "type": "string"
        },
        "location": {
            "type": "string"
        },
        "email": {
            "type": "string",
            "format": "email"
        },
        "linkedin": {
            "type": "string",
            "format": "uri"
        },
        "github": {
            "type": "string",
            "format": "uri"
        },
        "json_resume": {
            "type": "string",
            "format": "uri"
        },
        "education": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "degree": {
                        "type": "string"
                    },
                    "institution": {
                        "type": "string"
                    },
                    "location": {
                        "type": "string"
                    },
                    "year": {
                        "type": "string"
                    },
                    "major": {
                        "type": "string"
                    }
                },
                "additionalProperties": true,
                "required": [
                    "degree",
                    "institution"
                ]
            }
        },
        "skills": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "topic": {
                        "type": "string"
                    },
                    "skillset": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "additionalItems": false
                    }
                },
                "additionalProperties": true,
                "required": [
                    "topic",
                    "skillset"
                ]
            }
        },
        "experience": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "company": {
                        "type": "string"
                    },
                    "title": {
                        "type": "string"
                    },
                    "location": {
                        "type": "string"
                    },
                    "from": {
                        "type": "string"
                    },
                    "to": {
                        "type": "string"
                    },
                    "responsibilities": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "additionalItems": false
                    }
                },
                "additionalProperties": true,
                "required": [
                    "company",
                    "title",
                    "location",
                    "from",
                    "to",
                    "responsibilities"
                ]
            }
        }
    },
    "additionalProperties": false,
    "required": [
        "name",
        "email",
        "education",
        "skills",
        "experience"
    ]
}

=== atfaber/michelecasalgrandiresume/michelecasalgrandiresume.json
{
  "name": "Michele Casalgrandi",
  "location": "Orlando, FL",
  "email": "theinvalidemailtobereplacedwiththerealone@badbaddomain.bad",
  "linkedin": "https://www.linkedin.com/in/michele-casalgrandi",
  "github": "https://github.com/atfaber",
  "json_resume": "https://github.com/atfaber/michelecasalgrandiresume.json",
  "education": [
    {
      "degree": "Post-Graduate Program in Artificial Intelligence and Machine Learning",
      "institution": "University of Texas at Austin",
      "location": "Austin, TX",
      "year": "2021"
    },
    {
      "degree": "Bachelor of Science",
      "major": "Computer Science",
      "institution": "University of Central Florida",
      "location": "Orlando, FL"
    }
  ],
  "skills": [
    {
      "topic": "functional",
      "skillset": [
        "JIRA",
        "Confluence",
        "Agile/SCRUM",
        "Oracle Service Cloud"
      ]
    },
    {
      "topic": "technical",
      "skillset": [
        "Python",
        "Java",
        "C++",
        "Git",
        "Bitbucket",
        "Bamboo",
        "Jenkins",
        "Docker",
        "Kubernetes",
        "Helm",
        "Helmfile",
        "shell",
        "Linux"
      ]
    },
    {
      "topic": "cloud",
      "skillset": [
        "Azure",
        "AKS",
        "Oracle Cloud Infrastructure (OCI)"
      ]
    },
    {
      "topic": "machine_learning",
      "skillset": [
        "Object detection",
        "YOLOv7",
        "YOLOv8",
        "NCNN",
        "OpenCV",
        "OD CV models training",
        "scikit-learn",
        "Pandas"
      ]
    },
    {
      "topic": "data_science",
      "skillset": [
        "Exploratory Data Analysis (EDA)",
        "Seaborn",
        "Matplotlib",
        "Jupyter Notebook",
        "JupyterLab"
      ]
    }
  ],
  "experience": [
    {
      "company": "Cole Engineering Services, Inc.",
      "title": "Machine Learning Engineer",
      "location": "Orlando, Florida",
      "from": "Dec 2022",
      "to": "present",
      "responsibilities": [
        "Trained object detection models for low latency applications and improved their P/R performance.",
        "Evaluated performance of new OD models. Evaluated OD and segmentation models for automated annotation of field-collected images.",
        "Maintained image datasets, ensured data quality and identified areas of concern to inform future data collections and annotation methods.",
        "Migrated applications to SBC devices and built (Docker + QEMU and native) for target architecture.",
        "Identified and fixed integration issues and bugs in C, C++. Created and maintained scripts to start, monitor and track the health of applications.",
        "Integrated GPS/GNSS receivers and LTE board with embedded devices running Linux, improved the accuracy of location and the robustness of wireless connectivity.",
        "Wrote a Java declarative test framework to ensure accurate event processing by containerized services communicating via a message broker.",
        "Created and maintained Bamboo build pipelines for multiple projects."
      ]
    },
    {
      "company": "ORACLE America Inc.",
      "title": "Software Engineer, SCRUM Master",
      "location": "Orlando, Florida (remote)",
      "from": "Apr 2020",
      "to": "Mar 2022",
      "responsibilities": [
        "Implemented CI/CD pipelines to build and deploy microservices, targeting Kubernetes clusters using Jenkins, Helm, Helmfile in a DevOps, Platform-as-Code environment.",
        "Decreased time to discovery of defects and deployment issues by 2 days.",
        "Implemented automated security and compliance scans resulting in higher sprint velocity and lower technical debt.",
        "Led SCRUM activities for a team of senior software engineers for the delivery of a user action capture ETL/ELT data pipeline to Oracle Cloud Infrastructure (OCI) using containerized microservices.",
        "Managed backlog, stand-ups, sprint planning, sprint review, and retrospective ceremonies in collaboration with the product owner, development, and platform teams.",
        "Reduced stand-up calls duration by 70%."
      ]
    },
    {
      "company": "ORACLE America Inc.",
      "title": "Sr Development Manager",
      "location": "Orlando, Florida (remote)",
      "from": "Oct 2016",
      "to": "Mar 2020",
      "responsibilities": [
        "Managed a team of senior engineers in the delivery of Oracle Service Cloud SaaS UI features.",
        "Decreased time to resolutions of defects and service requests age by directly working and triaging customer service requests in collaboration with customer support.",
        "Provisioned and configured Service Cloud instances to create reproducible test cases. Reduced time-to-resolution of customer reported defects by 3+ days."
      ]
    },
    {
      "company": "ORACLE Corp",
      "title": "Development Manager",
      "location": "Orlando, Florida (remote)",
      "from": "Feb 2009",
      "to": "Sep 2016",
      "responsibilities": [
        "Managed a team of senior engineers in the rewrite, maintenance, and features implementation of a HIPAA-compliant attachment viewer and renderer for My Oracle Support (MOS) internal customer service application.",
        "Interfaced with end-users, integrating applications teams and executive stakeholders to prioritize, plan, and deliver new features.",
        "Introduced Agile SCRUM methodology resulting in shorter delivery cycles of product features."
      ]
    },
    {
      "company": "ORACLE Corp",
      "title": "Sr Principal Technical Support Engineer",
      "location": "Orlando, Florida",
      "from": "May 2002",
      "to": "Mar 2006",
      "responsibilities": [
        "Developed and released end-user self-service diagnostic tests for Oracle E-Business Suite.",
        "Established processes for the design, implementation, quality assurance, testing, and release of diagnostic tests.",
        "Outlined requirements for a diagnostic generator that reduced creation time from days to under two hours.",
        "Identified and implemented numerous process enhancements, including automation and automated diagnostics."
      ]
    },
    {
      "company": "ORACLE Corp",
      "title": "Sr Technical Support Engineer",
      "location": "Orlando, Florida",
      "from": "Mar 1996",
      "to": "Apr 2002",
      "responsibilities": [
        "Conducted analysis, root cause analysis (RCA), and resolution of technical issues for Oracle E-Business Suite manufacturing applications.",
        "Delivered training and consulting to support engineers, enabling them to resolve complex and advanced product issues."
      ]
    },
    {
      "company": "Lockheed Martin Corporation",
      "title": "Software Engineer (Contract, Intern)",
      "location": "Orlando, Florida",
      "from": "Aug 1994",
      "to": "Feb 1996",
      "responsibilities": [
        "Wrote system software for the AFIS fingerprint management system.",
        "Implemented a defect lifecycle tracking system."
      ]
    }
  ]
}
